services:
  rooktownbot:
    image: rooktownbot:latest
    container_name: rooktownbot-container
    restart: unless-stopped
    env_file: .env
    volumes:
      - /persistent/db:/resources/db
      - /persistent/leaderboards:/resources/leaderboards
      - /persistent/scoreboards:/resources/scoreboards

