name: RookTownBot CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: swaruph4/rooktownbot:latest

      - name: Stop and Remove Old Container
        run: |
          docker stop rooktownbot-container || true
          docker rm -f rooktownbot-container || true

      - name: Create .env file
        run: |
          echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" > .env
          echo "HENRIKDEV_API_KEY=${{ secrets.HENRIKDEV_API_KEY }}" >> .env
          echo "DATABASE_URL=jdbc:sqlite:/resources/db/RookTownBotDB" >> .env
          echo "LEADERBOARD_IMAGES_PATH=/resources/leaderboards" >> .env
          echo "SCOREBOARD_IMAGES_PATH=/resources/scoreboards" >> .env

      - name: Run compose file
        run: docker-compose up -d
